= Java Parallels

Set of utilities to ease running some common tasks with parallelism.

== Features

* Parallel Executor
    * Run a job using multiple threads: useful to run small performance and concurrency tests against backends (i.e. API, database...).
    * Collect statistics: error count, total/min/mav/avg times

* Parallel Files
    * Move files using multiple threads.

* Configuration
    * Utils to load values from environment variables or Java properties.

== Usage

The project is available through link:https://jitpack.io/#abelsromero/java-parallels/[].
To use the `main` branch version for example, with maven, just:

. Add JitPack's repository your `pom.xml`.
+
[,xml]
----
<repositories>
  <repository>
    <id>jitpack.io</id>
    <url>https://jitpack.io</url>
  </repository>
</repositories>
----

. The projects `master` dependency.
+
[,xml]
----
<dependency>
  <groupId>com.github.abelsromero</groupId>
  <artifactId>java-parallels</artifactId>
  <version>main-SNAPSHOT</version>
</dependency>
----

== Docker build

In case of issues with the dependency, you can install it locally:

. Clone repo
. run `./gradlew publishToMavenLocal`

Then, create a project importing the dependency as local.
For example, in Gradle

[,groovy]
----
repositories {
    mavenLocal()
----

[,groovy]
----
dependencies {
  implementation 'org.abelsromero.parallels:java-parallels:1.0.0-SNAPSHOT'
}
----

Finally, you can package your project with https://paketo.io/docs/howto/java/[Paketo Buildpack].

 pack build demo-parallels --path build/libs/MY_JAR.jar

Run your image locally to validate it's correctly created.

 docker run --rm demo-parallels:latest

=== Kubernetes deployment

Here are some advices to run your parallel executions in Kubernetes.

* Deployment creation

 kubectl create deployment parallels --image demo

[NOTE]
====
Remember if you want to use https://kind.sigs.k8s.io[KinD] for testing:

* Do not tag your image with `latest`.
* Load the image into the cluster with `kind load docker-image parallels:1.0.0`.
====

* Hot execution configuration

Load your configurations from environment variables, so that you can change them with

 kubectl set env deploy parallels MY_VAR=MY_VALUE

When updated, the pods will automatically restart with the new options.
Consider printing the configuration on the process start to validate them.
